artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://drive.google.com/file/d/1XGFjYm6NQapWFuS4kBrBUAb4epIt59GW/view?usp=sharing'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion